#+TITLE: PROJECT TASK TRACKING DOCUMENT
#+AUTHOR: DYLAN SKRAH
#DATE: <2021-12-09 Thu 10:30>



* TASK Build URL
** Build a dictionary of teams to their URL/HTML codes and find a way to access it to build the URL
Need a dictionary or list of `gamecode` to build the URL for a given game, which corresponds to the date the game is played.
*** TODO consume espn.com/nfl/schedule
**** HOLD need to filter byes for each weeks
 code written, just replicate for each week. Need to manually enter byes

** URL components
*** base = "https://scores.nbcsports.com/fb/"
*** section =
    box scores: boxscore.asp?
    play by play: pbp.asp?
*** gamecode/home/vis =
    "gamecode=<code>"
    "&home=<code>"
    "&vis=<code>"
*** In progress/done =
    In progress: "meta=true"
    done: "final=true#"
** Example URLs
*** game url (completed): https://scores.nbcsports.com/fb/boxscore.asp?gamecode=20211121016&home=16&vis=9&final=true#

*** game url (in progress):  https://scores.nbcsports.com/fb/boxscore.asp?gamecode=20211121024&home=24&vis=23&meta=true

* Functions
** Location/weather
*** Determine which arena the game is played at, time of game, and weather conditions
use 'home' team from URL dictionary
separate dictionary of teams and their home stadium location, consume weather conditions through separate soup object
** Box scores
*** Finish formatting
Need to distinguish between team-wide stats and individual player stats
** Play by play
*** Take output from play x play and scrape into pandas dataframe

* Scheduling
** How to run functions on all games currently in progress?
*** consume espn.com/nfl/schedule
